package de.ericmuench.appsfactorytesttask.model.runtime

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Artist(
    val mbid : String,
    val artistName : String,
    var description : String,
    val onlineUrl : String?,
    val imageUrl : String?,
    val albums : List<Album>
) : Parcelable{
    override fun equals(other: Any?): Boolean {
        if(other == null || other !is Artist){
            return false
        }

        return this.mbid == other.mbid && this.artistName == other.artistName
    }

    /**This hashcode function was autogenerated by*/
    override fun hashCode(): Int {
        var result = mbid.hashCode()
        result = 31 * result + artistName.hashCode()
        result = 31 * result + description.hashCode()
        result = 31 * result + (onlineUrl?.hashCode() ?: 0)
        result = 31 * result + albums.hashCode()
        return result
    }
}

@Parcelize
data class Album(
    val title : String,
    val artists : List<Artist>,
    var description : String,
    val onlineUrl : String?,
    val imgUrl : String?,
    val songs: List<Song>
) : Parcelable

@Parcelize
data class Song(
    val title: String,
    val onlineUrl: String?
) : Parcelable

data class ArtistSearchResult(
    val totalResults : Int,
    val startPage : Int,
    val startIndex : Int,
    val itemsPerPage : Int,
    val items: List<Artist>
)