package de.ericmuench.appsfactorytesttask.model.runtime

import android.os.Parcelable
import kotlinx.parcelize.Parcelize


@Parcelize
data class Artist(
    val mbid : String?,
    val artistName : String,
    val description : String,
    val onlineUrl : String?,
    val imageUrl : String?,
) : Parcelable{
    override fun equals(other: Any?): Boolean {
        if(other == null || other !is Artist){
            return false
        }

        var mbIdCheck = true
        if(this.mbid != null && other.mbid != null){
            mbIdCheck = this.mbid == other.mbid
        }

        return mbIdCheck && this.artistName == other.artistName
    }

    /**This hashcode function was autogenerated by Android Studio*/
    override fun hashCode(): Int {
        var result = mbid.hashCode()
        result = 31 * result + artistName.hashCode()
        result = 31 * result + description.hashCode()
        result = 31 * result + (onlineUrl?.hashCode() ?: 0)
        return result
    }
}

@Parcelize
data class Album(
    val mbid : String?,
    val title : String,
    val description : String,
    val onlineUrl : String?,
    val imgUrl : String?,
    val artistName : String,
    val songs: List<Song>
) : Parcelable{
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Album) return false

        if (mbid != other.mbid) return false
        if (title != other.title) return false
        if (description != other.description) return false
        if (onlineUrl != other.onlineUrl) return false
        if (imgUrl != other.imgUrl) return false
        if (artistName != other.artistName) return false
        if (songs != other.songs) return false

        return true
    }

    override fun hashCode(): Int {
        var result = mbid?.hashCode() ?: 0
        result = 31 * result + title.hashCode()
        result = 31 * result + description.hashCode()
        result = 31 * result + (onlineUrl?.hashCode() ?: 0)
        result = 31 * result + (imgUrl?.hashCode() ?: 0)
        result = 31 * result + artistName.hashCode()
        result = 31 * result + songs.hashCode()
        return result
    }
}

@Parcelize
data class Song(
    val title: String,
    val onlineUrl: String?
) : Parcelable{
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Song) return false

        if (title != other.title) return false
        if (onlineUrl != other.onlineUrl) return false

        return true
    }

    override fun hashCode(): Int {
        var result = title.hashCode()
        result = 31 * result + (onlineUrl?.hashCode() ?: 0)
        return result
    }
}


data class ArtistSearchResult(
    val totalResults : Int,
    val startPage : Int,
    val startIndex : Int,
    val itemsPerPage : Int,
    val items: List<Artist>
)

data class TopAlbumOfArtistResult(
    val albums : List<Album>,
    val page: Int,
    val totalPages : Int,
    val perPage: Int
)