package de.ericmuench.appsfactorytesttask.model.runtime

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Artist(
    val mbid : String?,
    val artistName : String,
    var description : String,
    val onlineUrl : String?,
    val imageUrl : String?,
) : Parcelable{
    override fun equals(other: Any?): Boolean {
        if(other == null || other !is Artist){
            return false
        }

        var mbIdCheck = true
        if(this.mbid != null && other.mbid != null){
            mbIdCheck = this.mbid == other.mbid
        }

        return mbIdCheck && this.artistName == other.artistName
    }

    /**This hashcode function was autogenerated by Android Studio*/
    override fun hashCode(): Int {
        var result = mbid.hashCode()
        result = 31 * result + artistName.hashCode()
        result = 31 * result + description.hashCode()
        result = 31 * result + (onlineUrl?.hashCode() ?: 0)
        return result
    }
}

@Parcelize
data class Album(
    val mbid : String?,
    val title : String,
    var description : String,
    val onlineUrl : String?,
    val imgUrl : String?,
    val artistName : String,
    val songs: List<Song>
) : Parcelable

@Parcelize
data class Song(
    val title: String,
    val onlineUrl: String?
) : Parcelable


data class ArtistSearchResult(
    val totalResults : Int,
    val startPage : Int,
    val startIndex : Int,
    val itemsPerPage : Int,
    val items: List<Artist>
)

data class TopAlbumOfArtistResult(
    val albums : List<Album>,
    val page: Int,
    val totalPages : Int,
    val perPage: Int
)